# YOUR NAME OR TITLE OF YOUR SITE
name: Payme

# YOUR BRAND/PERSONAL TAGLINE
tagline: use below options to pay me as by ur convenience

# YOUR/BRAND IMAGE URL
Image_URL:

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # gpay
  - Name: google pay
    URL: upi://pay?pa=niranrnk003-2@oksbi&pn=Niranjan Raj&aid=uGICAgMCgmeC6Kw
    Color: '#ffffff'
    Icon-Class: fab fa-google
    Text_Color: '#5d5d65'
    # paytm
  - Name: Paytm
    URL: upi://pay?pa=9445240637@paytm&pn=PaytmUser&mc=0000&mode=02&purpose=00&orgid=159761
    Color: '#01b0e3'
    Text_Color: '#ffffff'

    # phonepe
  - Name: PhonePe
    URL:  upi://pay?pa=9445240637@ybl&pn=**0637&mc=0000&mode=02&purpose=00
    Color: '#5c249a'
    Text_Color: '#ffffff'

    # amazonpay
  - Name: amazon pay
    URL: 
    Color: '#2d333d'
    Icon-Class: fab fa-amazon-pay

    # INSTAGRAM
  # - Name: Instagram
  #   URL: https://www.instagram.com
  #   Username: mr.silver_shades345
  #   Color: '#DD2A7B'
  #   Icon-Class: fab fa-instagram  

    # EMAIL
  # - Name: Email
  #   URL: 'mailto:niranrnk003@gmail.com'
  #   Icon-Class: fas fa-envelope
  #   Color: '#e17055'
  #   Text_Color: '#ffffff'

    # GITHUB
  # - Name: GitHub
  #   URL: http://github.com
  #   Username: NiranjanRaj345
  #   Color: '#6e5494'
  #   Icon-Class: fab fa-github

    # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+919445240637'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

 # FACEBOOK
  # - Name: Facebook
  #   URL: https://www.facebook.com
  #   Username: NiranjanRaj345
  #   Color: '#3b5998'
  #   Icon-Class: fab fa-facebook
   
    # REDDIT
  # - Name: Reddit
  #   URL: http://reddit.com/u
  #   Username: pranav__-
  #   Color: '#FF4500'
  #   Icon-Class: fab fa-reddit-alien

    # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 'Mr.Monk_#3391'
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # SPOTIFY
  # - Name: Spotify
  #   URL: http://open.spotify.com/user
  #   Username: frr0m29k7gqij9206pp241ode
  #   Color: '#1DB954'
  #   Icon-Class: fab fa-spotify

    # PINTEREST
  # - Name: Pinterest
  #   URL: https://pinterest.com
  #   Username: 'niranjan345'
  #   Color: '#E60023'
  #   Icon-Class: fab fa-pinterest
  
    # LINKEDIN
  # - Name: LinkedIn
  #   URL: https://www.linkedin.com/in
  #   Username: -niranjan
  #   Color: '#2867B2'
  # Icon-Class: fab fa-linkedin-in

    # STEAM
  # - Name: Steam
  #   URL: https://steamcommunity.com/profiles/ 
  #   Username: 76561199142461956/
  #   Color: '#152e5d'
  #   Icon-Class: fab fa-steam-symbol

    # DEVIANTART
  # - Name: DeviantArt
  #   URL: https://www.deviantart.com
  #   Username: dark789shadow
  #   Icon-Class: fab fa-deviantart
  #   Color: '#05CC46'
  #   Text_Color: '#ffffff'

    # TWITCH
  # - Name: Twitch
  #   URL: 'https://twitch.tv'
  #   Username: niranjanraj345
  #   Icon-Class: fab fa-twitch
  #   Color: '#9147fe'
  #   Text_Color: '#ffffff'

    #CLUBHOUSE
  # - Name: Clubhouse
  #   URL: https://www.clubhouse.com
  #   Username: '@harsh98trivedi'
  #   Color: '#f1c40f'
  #   Icon-Class: fas fa-hand-paper -mt-0.5

   

    # VIMEO
  # - Name: Vimeo
  #   URL: 'https://vimeo.com'
  #   Username: harshtrivedi
  #   Icon-Class: fab fa-vimeo-v
  #   Color: '#1ab7ea'
  #   Text_Color: '#ffffff'

    # MESSENGER
  # - Name: Messenger
  #   URL: https://m.me
  #   Username: theharshtrivedi
  #   Color: '#006AFF'
  #   Icon-Class: fab fa-facebook-messenger

    # SIGNAL
  # - Name: Signal
  #   URL: https://signal.org
  #   Username: '+19445240637'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

    # BEHANCE
  # - Name: Behance
  #   URL: https://www.behance.net
  #   Username: harsh98trivedi
  #   Color: '#1769ff'
  #   Icon-Class: fab fa-behance

    # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # FIGMA
  # - Name: Figma
  #   URL: https://www.figma.com
  #   Username: '@harshtrivedi'
  #   Icon-Class: fab fa-figma
  #   Color: '#ff2865'
  #   Text_Color: '#ffffff'

    # SOUNDCLOUD
  # - Name: SoundCloud
  #   URL: https://www.soundcloud.com
  #   Username: harsh98trivedi
  #   Color: '#FE5000'
  #   Icon-Class: fab fa-soundcloud

    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

    # MEDIUM
  # - Name: Medium
  #   URL: 'https://medium.com'
  #   Username: '@harsh98trivedi'
  #   Icon-Class: fab fa-medium-m
  #   Color: '#00ab6c'
  #   Text_Color: '#ffffff'

    # DEV.TO
  # - Name: Dev.to
  #   URL: 'https://dev.to'
  #   Username: harsh98trivedi
  #   Icon-Class: fab fa-dev
  #   Color: '#ffffff'
  #   Text_Color: '#000000'

    # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

    # CUSTOM LINK
  # - Name: Blog
  #   URL: https://harsh98trivedi.github.io/blog
  #   Icon-Class: fas fa-link
  #   Color: '#ffb142'
  #   Text_Color: '#ffffff'

  # - Name: Links
  #   URL: https://github.com/harsh98trivedi/links
  #   Icon-Class: fas fa-link
  #   Color: '#d94869'
  #   Text_Color: '#ffffff'

    # BUY ME A COFFEE
  # - Name: BuyMeACoffee
  #   URL: 'https://buymeacoffee.com'
  #   Username: NiranjanRaj
  #   Icon-Class: fas fa-mug-hot
  #   Color: '#FFDD00'
  #   Text_Color: '#000000'    
 
# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
# footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
