# YOUR NAME OR TITLE OF YOUR SITE
name: pay me

# YOUR BRAND/PERSONAL TAGLINE
tagline: use below options to pay me as by your convenience

# YOUR/BRAND IMAGE URL
# Image_URL:

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # gpay
  - Name: Google Pay
    URL: upi://pay?pa=niranrnk003-2@oksbi&pn=Niranjan Raj&aid=uGICAgMCgmeC6Kw
    Color: '#ffffff'
    Icon-Class: fab fa-google-pay
    Text_Color: '#5d5d65'
    # paytm
  - Name: Paytm
    URL: upi://pay?pa=9445240637@paytm&pn=PaytmUser&mc=0000&mode=02&purpose=00&orgid=159761
    Color: '#1b2a8c'
    Text_Color: '#06bbf3'

    # phonepe
  - Name: PhonePe
    URL:  upi://pay?pa=9445240637@ybl&pn=**0637&mc=0000&mode=02&purpose=00
    Color: '#5c249a'
    Text_Color: '#ffffff'

    # amazonpay
  - Name: amazon pay
    URL: upi://pay?pa=9445240637@apl&tn=Send Payment&pn=Lakshmi Priya Rajkumar
    Color: '#2d333d'
    Icon-Class: fab fa-amazon-pay

    # BUY ME A COFFEE
  # - Name: BuyMeACoffee
  #   URL: 'https://buymeacoffee.com'
  #   Username: NiranjanRaj
  #   Icon-Class: fas fa-mug-hot
  #   Color: '#FFDD00'
  #   Text_Color: '#000000'    
 
footer: 'Yes'
# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
